name: spacex_api
description: A package created to be a client wrapper for the SpaceX API hosted
  at https://github.com/r-spacex/SpaceX-API
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.1
  dio_cache_interceptor_hive_store: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
